version: '3.8'

services:
  mysqldb:
    image: mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DB
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - 3307:3306
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 3000:3000

