version: '3.8'

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_DATABASE=blog_db
      - MYSQL_USER=blog_user
      - MYSQL_PASSWORD=blog_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - 3307:3306
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

